version: '3.8'
volumes:
  db_data: {}

services:
  php:  
    container_name: hammerbro-fpm
    build:
      context: .
      dockerfile: .docker/files/Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - DISPLAY_ERRORS=true
      - XDEBUG_CONFIG="idekey=PHPSTORM"
    ports:
      - 9000
    depends_on:
      - "db"

  db: 
    container_name: hammerbro-db
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hammerbro
      - MYSQL_USER=hammerbro
      - MYSQL_PASSWORD=hammerbro

  nginx:
    container_name: hammerbro-nginx
    image: nginx:latest
    links:
      - php
    ports:
      - 80:80
    volumes:
      - .docker/files/nginx-dev.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
